'\" t
.\"     Title: trace-cmd-dump
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/31/2022
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TRACE\-CMD\-DUMP" "1" "03/31/2022" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
trace-cmd-dump \- show a meta data from a trace file, created by trace\-cmd record
.SH "SYNOPSIS"
.sp
\fBtrace\-cmd dump\fR [\fIOPTIONS\fR] [\fIinput\-file\fR]
.SH "DESCRIPTION"
.sp
The trace\-cmd(1) dump command will display the meta data from a trace file created by trace\-cmd record\&.
.SH "OPTIONS"
.PP
\fB\-i\fR \fIinput\-file\fR
.RS 4
By default, trace\-cmd dump will read the file
\fItrace\&.dat\fR\&. But the
\fB\-i\fR
option open up the given
\fIinput\-file\fR
instead\&. Note, the input file may also be specified as the last item on the command line\&.
.RE
.PP
\fB\-v\fR, \fB\-\-validate\fR
.RS 4
Check if the input file is a valid trace file, created by trace\-cmd\&.
.RE
.PP
\fB\-\-summary\fR
.RS 4
Print a meta data summary \- initial format and a short description of each file section\&. This is the default action, if no arguments are specified\&.
.RE
.PP
\fB\-\-head\-page\fR
.RS 4
Print the header page information, stored in the file\&.
.RE
.PP
\fB\-\-head\-event\fR
.RS 4
Print the event header information, stored in the file\&.
.RE
.PP
\fB\-\-ftrace\-events\fR
.RS 4
Print formats of ftrace specific events\&.
.RE
.PP
\fB\-\-systems\fR
.RS 4
Print information of event systems, stored in the file \- name and number of events for each system\&.
.RE
.PP
\fB\-\-events\fR
.RS 4
Print formats of all events, stored in the file\&.
.RE
.PP
\fB\-\-kallsyms\fR
.RS 4
Print information of the mapping of function addresses to the function names\&.
.RE
.PP
\fB\-\-printk\fR
.RS 4
Print trace_printk() format strings, stored in the file\&.
.RE
.PP
\fB\-\-cmd\-lines\fR
.RS 4
Print mapping a PID to a process name\&.
.RE
.PP
\fB\-\-options\fR
.RS 4
Print all options, stored in the file\&.
.RE
.PP
\fB\-\-flyrecord\fR
.RS 4
Print the offset and the size of tracing data per each CPU\&.
.RE
.PP
\fB\-\-all\fR
.RS 4
Print all meta data from the file\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print usage information\&.
.RE
.SH "EXAMPLES"
.sp
# trace\-cmd dump \-\-summary \-i trace\&.dat
.sp
.if n \{\
.RS 4
.\}
.nf
Tracing meta data in file trace\&.dat:
       [Initial format]
               6       [Version]
               0       [Little endian]
               8       [Bytes in a long]
               4096    [Page size, bytes]
       [Header info, 205 bytes]
       [Header event, 205 bytes]
       [Ftrace format, 15 events]
       [Events format, 2 systems]
       [Kallsyms, 7144493 bytes]
       [Trace printk, 2131 bytes]
       [Saved command lines, 117 bytes]
       8 [CPUs with tracing data]
       [12 options]
       [Flyrecord tracing data]
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
# trace\-cmd dump \-\-flyrecord \-i trace\&.dat
        [Flyrecord tracing data]
                 7176192 0      [offset, size of cpu 0]
                 7176192 0      [offset, size of cpu 1]
                 7176192 0      [offset, size of cpu 2]
                 7176192 4096   [offset, size of cpu 3]
                 7180288 4096   [offset, size of cpu 4]
                 7184384 0      [offset, size of cpu 5]
                 7184384 0      [offset, size of cpu 6]
                 7184384 0      [offset, size of cpu 7]
.fi
.if n \{\
.RE
.\}
.sp
# trace\-cmd dump \-\-summary \-\-systems \-i trace\&.dat
.sp
.if n \{\
.RS 4
.\}
.nf
Tracing meta data in file trace\&.dat:
       [Initial format]
               6       [Version]
               0       [Little endian]
               8       [Bytes in a long]
               4096    [Page size, bytes]
       [Header info, 205 bytes]
       [Header event, 205 bytes]
       [Ftrace format, 15 events]
       [Events format, 3 systems]
               sched 23 [system, events]
               irq 5 [system, events]
               kvm 70 [system, events]
       [Kallsyms, 7144493 bytes]
       [Trace printk, 2131 bytes]
       [Saved command lines, 157 bytes]
       8 [CPUs with tracing data]
       [11 options]
       [Flyrecord tracing data]
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
# trace\-cmd dump \-\-summary \-\-systems \-i trace\&.dat
File trace\&.dat is a valid trace\-cmd file
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
trace\-cmd(1), trace\-cmd\&.dat(1)
.SH "AUTHOR"
.sp
\fBSteven Rostedt\fR <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>, author of \fBtrace\-cmd\fR\&. \fBTzvetomir Stoyanov\fR <\m[blue]\fBtz\&.stoyanov@gmail\&.com\fR\m[]\&\s-2\u[2]\d\s+2>, author of this man page\&.
.SH "RESOURCES"
.sp
\m[blue]\fBhttps://git\&.kernel\&.org/pub/scm/utils/trace\-cmd/trace\-cmd\&.git/\fR\m[]
.SH "COPYING"
.sp
Copyright (C) 2010 Red Hat, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
.IP " 2." 4
tz.stoyanov@gmail.com
.RS 4
\%mailto:tz.stoyanov@gmail.com
.RE
