'\" t
.\"     Title: libtracecmd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/31/2022
.\"    Manual: libtracefs Manual
.\"    Source: libtracefs
.\"  Language: English
.\"
.TH "LIBTRACECMD" "3" "03/31/2022" "libtracefs" "libtracefs Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
libtracecmd \- trace\-cmd library APIs
.SH "SYNOPSIS"
.sp
.nf
\fB#include <trace\-cmd\&.h>\fR

Open and close trace file:
        struct tracecmd_input *\fBtracecmd_open\fR(const char *\fIfile\fR, int \fIflags\fR);
        struct tracecmd_input *\fBtracecmd_open_fd\fR(int \fIfd\fR, int \fIflags\fR);
        struct tracecmd_input *\fBtracecmd_open_head\fR(const char *\fIfile\fR, int \fIflags\fR);
        void \fBtracecmd_close\fR(struct tracecmd_input *\fIhandle\fR);

Read tracing records from a trace file:
        int \fBtracecmd_init_data\fR(struct tracecmd_input *\fIhandle\fR);
        struct tep_record *\fBtracecmd_read_cpu_first\fR(struct tracecmd_input *\fIhandle\fR, int \fIcpu\fR);
        struct tep_record *\fBtracecmd_read_data\fR(struct tracecmd_input *\fIhandle\fR, int \fIcpu\fR);
        struct tep_record *\fBtracecmd_read_at\fR(struct tracecmd_input *\fIhandle\fR, unsigned long long \fIoffset\fR, int *\fIcpu\fR);
        void \fBtracecmd_free_record\fR(struct tep_record *\fIrecord\fR);
        struct tep_handle *\fBtracecmd_get_tep\fR(struct tracecmd_input *\fIhandle\fR);

Read tracing instances from a trace file:
        int \fBtracecmd_buffer_instances\fR(struct tracecmd_input *\fIhandle\fR);
        const char *\fBtracecmd_buffer_instance_name\fR(struct tracecmd_input *\fIhandle\fR, int \fIindx\fR);
        struct tracecmd_input *\fBtracecmd_buffer_instance_handle\fR(struct tracecmd_input *\fIhandle\fR, int \fIindx\fR);

Get traceing peer information from a trace file:
        unsigned long long \fBtracecmd_get_traceid\fR(struct tracecmd_input *\fIhandle\fR);
        int \fBtracecmd_get_guest_cpumap\fR(struct tracecmd_input *\fIhandle\fR, unsigned long long \fItrace_id\fR, const char **\fIname\fR, int *\fIvcpu_count\fR, const int **\fIcpu_pid\fR);
.fi
.SH "DESCRIPTION"
.sp
The libtracecmd(3) library provides APIs to read, parse and write \fItrace\-cmd\&.dat(5)\fR files, recorded with \fItrace\-cmd(1)\fR application and containing tracing information from ftrace, the official Linux kernel tracer\&.
.SH "FILES"
.sp
.if n \{\
.RS 4
.\}
.nf
\fBtrace\-cmd\&.h\fR
        Header file to include in order to have access to the library APIs\&.
\fB\-ltracecmd\fR
        Linker switch to add when building a program that uses the library\&.
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
\fIlibtraceevent(3)\fR \fIlibtracefs(3)\fR \fItrace\-cmd(1)\fR \fItrace\-cmd\&.dat(5)\fR
.SH "AUTHOR"
.sp
.if n \{\
.RS 4
.\}
.nf
\fBSteven Rostedt\fR <\m[blue]\fBrostedt@goodmis\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
\fBTzvetomir Stoyanov\fR <\m[blue]\fBtz\&.stoyanov@gmail\&.com\fR\m[]\&\s-2\u[2]\d\s+2>
.fi
.if n \{\
.RE
.\}
.SH "REPORTING BUGS"
.sp
Report bugs to <\m[blue]\fBlinux\-trace\-devel@vger\&.kernel\&.org\fR\m[]\&\s-2\u[3]\d\s+2>
.SH "LICENSE"
.sp
libtracecmd is Free Software licensed under the GNU LGPL 2\&.1
.SH "RESOURCES"
.sp
\m[blue]\fBhttps://git\&.kernel\&.org/pub/scm/utils/trace\-cmd/trace\-cmd\&.git/\fR\m[]
.SH "COPYING"
.sp
Copyright (C) 2020 VMware, Inc\&. Free use of this software is granted under the terms of the GNU Public License (GPL)\&.
.SH "NOTES"
.IP " 1." 4
rostedt@goodmis.org
.RS 4
\%mailto:rostedt@goodmis.org
.RE
.IP " 2." 4
tz.stoyanov@gmail.com
.RS 4
\%mailto:tz.stoyanov@gmail.com
.RE
.IP " 3." 4
linux-trace-devel@vger.kernel.org
.RS 4
\%mailto:linux-trace-devel@vger.kernel.org
.RE
